name: build
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push as dev image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: abu33/helloapp:dev-${{ github.sha }}
      -
        name: Scan image for vulnerabilities
        uses: Azure/container-scan@v0
        with:
          image-name: abu33/helloapp:dev-${{ github.sha }}
          run-quality-checks: false
