name: deploy
on:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Start minikube
        uses: medyagh/setup-minikube@master
      -
        name: Create Kubernetes manifests
        uses: Azure/k8s-bake@v2.2
        with:
          renderEngine: "helm"
          helmChart: "./helloapp-chart/"
          overrides: 'image.tag:stable-1.0-${{ github.sha }}'
          helm-version: "latest"
      -
        name: Deploy helloapp chart
        uses: Azure/k8s-deploy@v1
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
