name: build-deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ABu33/devops-task/.github/workflows/build.yaml@master
    secrets: inherit
  deploy:
    uses: ABu33/devops-task/.github/workflows/deploy.yaml@master
    needs: build
